[package]
name = "ebi-to-gcp"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.41", features = ["derive"] }
deltalake = "0.26.2"
polars = { version = "0.49.1", features = ["lazy", "strings"] }
regex = "1.11.1"
serde = "1.0.219"
serde_yaml = "0.9.34"
walkdir = "2.5.0"
